query_insert = "INSERT INTO todo (name, description, done, date) VALUES (%s, %s, %s, %s)"
query_create = "CREATE TABLE if not exists todo (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY , name VARCHAR(50), description VARCHAR(250), done BOOLEAN, date DATE)"
query_select_true = "SELECT * FROM todo WHERE done = true"
query_select_false = "SELECT * FROM todo WHERE done = false"
